function S = propagator_sphere_labframe_general(cl, wavelength, epsilon, ...
    medium, AlphaBlocks, N_esa, N_mie, N_theta, ...
    stPiTauMie, stPiTauESA)
% general case where dipoles aren't necessarily at a fixed radial distance

% ...

end
